library(shiny)
library(shinyjs)
library(mcr)
library(shinydashboard)
library(rhandsontable)
library(dplyr)
library(rmarkdown)
library(readxl)
library(scales)
library(kableExtra)
library(pander)
library(DT)
library(sendmailR)
source("www/tabitem_info.R")
source("www/tabitem_data.R")
source("www/tabitem_moddata.R")
source("www/funs.R")
source("www/tabitem_stats.R")
source("www/tabitem_download.R")
source("www/tabitem_subitem1.R")
source("www/tabitem_subitem2.R")
source("www/tabitem_subitem3.R")
source("www/tabitem_subitem4.R")

# Source modules
source("modules/infra/logging.R")
source("modules/infra/error_handling.R")
source("modules/infra/config_loader.R")
source("modules/infra/log_viewer.R")

source("modules/domain/data_processing.R")
source("modules/domain/reactive_data.R")
source("modules/domain/plot_generation.R")
source("modules/domain/ui_reactive.R")
source("modules/domain/download_handler.R")
source("modules/domain/validation.R")
source("modules/domain/admin_panel.R")
