tabItem_info <- function(){ 
   tabItem(tabName = "info",
        h2("Method Comparison and Bias Estimation Using R and Shiny"),
        br(),
        h4('This website is a product of R programming language(1) and shiny(2) web application framework. Statistics are based on mcr package(3). Shinydashboard(4), rhandsontable(5) and pander(6) are used for website construction. Rmarkdown(7) is used for converting results into document files.'),
        #              br(),
        h4('How to:'),
        h4('1. Copy/paste or manually enter your data using the "Data" tab and 
                 enter method names.'),
        h4('2. See your data distribution and choose statistical tests using the "Plots" tab.'),
        h4('3. See the statistical evaluation of the selected data using the "Statistics" tab and 
                 download using the "Download" tab.'),
        br(),
        h4('References and packages:'),
        h5("1. R: A language and environment for statistical computing. 
                 R Foundation for Statistical Computing, Vienna, Austria.",
           a('https://www.R-project.org',
             href = "https://www.R-project.org")),
        h5("2. shiny: Web Application Framework for R.",
           a("http://CRAN.R-project.org/package=shiny", 
             href = "http://CRAN.R-project.org/package=shiny")),
        h5("3. mcr: Method Comparison Regression.",
           a('http://CRAN.R-project.org/package=mcr',
             href = "http://CRAN.R-project.org/package=mcr")),
        h5("4. shinydashboard: Create Dashboards with 'Shiny'.",
           a('http://rstudio.github.io/shinydashboard',
             href = "http://rstudio.github.io/shinydashboard")),
        h5("5. rhandsontable: Interface to the 'Handsontable.js' Library.",
           a('http://jrowen.github.io/rhandsontable',
             href = "http://jrowen.github.io/rhandsontable")),
        h5("6. pander: An R Pandoc Writer.",
           a('http://rapporter.github.io/pander',
             href = "http://rapporter.github.io/pander")),
        h5("7. rmarkdown: Dynamic Documents for R.",
           a('http://rmarkdown.rstudio.com',
             href = "http://rmarkdown.rstudio.com")),
        br(),
        h4('This app is based on the Method Comparison app developed by Burak Bahar')
)}
