name: R-CMD-check-minimal

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for systemfonts
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libfreetype6-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            testthat
            dplyr
            kableExtra
          cache: true

      - name: Run tests
        run: testthat::test_dir("tests/testthat")
        shell: Rscript {0}
