name: R-CMD-check

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install packages and run tests
        run: |
          install.packages(c(
            "shiny",
            "mcr",
            "shinydashboard",
            "rhandsontable",
            "dplyr",
            "rmarkdown",
            "readxl",
            "scales",
            "systemfonts", 
            "textshaping",
            "svglite",
            "kableExtra",
            "pander",
            "testthat"
          ), repos = "https://cloud.r-project.org")
          testthat::test_dir("tests/testthat")
        shell: Rscript {0}
