name: R-CMD-check

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install required packages
        run: |
          install.packages(c(
            "shiny",
            "mcr",
            "kableExtra",
            "shinydashboard",
            "rhandsontable",
            "dplyr",
            "rmarkdown"
          ), repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Run tests
        run: |
          install.packages("testthat", repos = "https://cloud.r-project.org")
          testthat::test_dir("tests/testthat")
        shell: Rscript {0}
